### ISSUE TITLE
 enableScrollSpy 这个属性我为啥设置了不生效呢，没有出现在可见区域就已经滚动完了 

### ISSUE THREAD

**Issue by mmclofe** [jizai1125/vue-countup-v3#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jizai1125** [comment]
没问题呀 https://codesandbox.io/s/vue-countup-v3-demo-enablescrollspy-qnvtyh

**Comment by mmclofe** [comment]
我用的nuxt3不知道是不是服务端渲染的原因

> 没问题呀 https://codesandbox.io/s/vue-countup-v3-demo-enablescrollspy-qnvtyh

**Comment by jizai1125** [comment]
> 我用的nuxt3不知道是不是服务端渲染的原因
> 
> > 没问题呀 https://codesandbox.io/s/vue-countup-v3-demo-enablescrollspy-qnvtyh

在 Nuxt 中也没问题呀  https://stackblitz.com/edit/github-rxehzt?file=app.vue
