### ISSUE TITLE
end-val发生变化会从0开始

### ISSUE THREAD

**Issue by blackawn** [jizai1125/vue-countup-v3#13]
只设置end-val属性，end-val发生变化时不能从上次的值开始执行动画了么，会从0开始步进

**Comment by jizai1125** [comment]
是的，有两种方式可以解决，一种是维护 `start-val` 和 `end-val`;
```vue
<script setup lang="ts">
const startValRef = ref(0)
const endValRef = ref(2000)

const incrementalUpdate = () => {
  startValRef.value = endVal.value
  endValRef.value += 1000
}
</script>

<template>
  <count-up  
    :start-val="startValRef" 
    :end-val="endValRef">
  </count-up>
</template>
```
一种是使用 `update` 方法;
```vue
<script setup lang="ts">
const startValRef = ref(2000)

let countUp;
const onInit = (ctx) => {
  countUp = ctx;
};
const update = () => {
  countUp?.update(4000)
}
</script>

<template>
<button @click="update">update</button>
  <count-up  
    :end-val="endValRef"
    @init="onInit"
    >
  </count-up>
</template>

**Comment by blackawn** [comment]
我回退到1.1.0版本是可以的哈

**Comment by blackawn** [comment]
> 是的，有两种方式可以解决，一种是维护 `start-val` 和 `end-val`;
> 
> ```
> <script setup lang="ts">

> const startValRef = ref(0)
> const endValRef = ref(2000)
> 
> const incrementalUpdate = () => {
>   startValRef.value = endVal.value
>   endValRef.value += 1000
> }
> </script>
> 
> <template>
>   <count-up  
>     :start-val="startValRef" 
>     :end-val="endValRef">
>   </count-up>
> </template>
> ```
> 
> 一种是使用 `update` 方法;
> 
> ```
> <script setup lang="ts">
> const startValRef = ref(2000)
> 
> let countUp;
> const onInit = (ctx) => {
>   countUp = ctx;
> };
> const update = () => {
>   countUp?.update(4000)
> }
> </script>
> 
> <template>
> <button @click="update">update</button>
>   <count-up  
>     :end-val="endValRef"
>     @init="onInit"
>     >
>   </count-up>
> </template>
> ```


我回退到1.1.0版本是可以的哈

**Comment by blackawn** [comment]
@jizai1125 我回退到1.1.0版本是可以的哈

**Comment by laurensV** [comment]
Both those two solution are quite annoying to implement, especially with lots of countup elements (doubling the amount of variables needed)..

Can't we solve it like the old version where if you don't specify the start value it will just use the previous end-value? Or the start value is only used the first time?

I think it should use the 'update' method whenever the end value changes, so that way we don't have to create the update value onInit for every count-up element

**Comment by jizai1125** [comment]
> Both those two solution are quite annoying to implement, especially with lots of countup elements (doubling the amount of variables needed)..
> 
> Can't we solve it like the old version where if you don't specify the start value it will just use the previous end-value? Or the start value is only used the first time?
> 
> I think it should use the 'update' method whenever the end value changes, so that way we don't have to create the update value onInit for every count-up element

Indeed, I will find a way to resolve this issue.
