### ISSUE TITLE
千分符没有生效

### ISSUE THREAD

**Issue by xiaohai18** [jizai1125/vue-countup-v3#14]
<count-up :end-val="count" :useIndianSeparators="false" :useGrouping="false" separator="_"></count-up>
<img width="163" alt="image" src="https://github.com/jizai1125/vue-countup-v3/assets/16174674/7708fa6c-1b91-4954-9cd1-1996df04802c">

千分符没有生效,我想取消掉千分符没有生效,换一个千分符测试也没有生效

**Comment by shen-lan** [comment]
怎么解决的

**Comment by jizai1125** [comment]
> 怎么解决的

看文档，使用 `options`
