### ISSUE TITLE
vite打包报错

### ISSUE THREAD

**Issue by TY-LIU** [jizai1125/vue-countup-v3#15]
**Describe the bug**
### vite构建vue3项目时报以下错误
```
 Could not find a declaration file for module 'vue-countup-v3'. '本机路径/node_modules/.pnpm/vue-countup-v3@1.3.0_vue@3.3.4/node_modules/vue-countup-v3/dist/vue-count
up-v3.es.js' implicitly has an 'any' type.
  There are types at '本机路径/node_modules/vue-countup-v3/dist/countup.vue.d.ts', but this result could not be resolved when respecting package.json "exports". The 'vue-countup-v3' library may need to update its package.json or typings. 
```
使用的时候，编译器会报错。但是不会影响运行，只是构建的时候会失败
![image](https://github.com/jizai1125/vue-countup-v3/assets/29595097/2ef233cb-9222-41ae-93ac-222f8e93888c)
目前的解决方案是在tsconfig中，配置
```ts
{
    "compilerOptions":{
        "noImplicitAny":false
    }
}
```

**Comment by jizai1125** [comment]
能给个复现么，我这没发现有问题

**Comment by TY-LIU** [comment]
> 能给个复现么，我这没发现有问题

我刚刚修改了下issue，你可能配置了我修改部分的代码

**Comment by jizai1125** [comment]
> > 能给个复现么，我这没发现有问题
> 
> 我刚刚修改了下issue，你可能配置了我修改部分的代码

这是主动关掉 ts 报错了，我还是想看看啥原因，你的项目能给个 demo 么，看报错是好像是声明文件没被 resolve 到

**Comment by TY-LIU** [comment]
> > > 能给个复现么，我这没发现有问题
> > 
> > 
> > 我刚刚修改了下issue，你可能配置了我修改部分的代码
> 
> 这是主动关掉 ts 报错了，我还是想看看啥原因，你的项目能给个 demo 么，看报错是好像是声明文件没被 resolve 到

搞一个在线demo看不到问题，你可以按照我给的步骤本地生成一个demo
*  npm create vue@latest
* ADD TS, ADD ESLint Prettier 
*  cd,  npm i
* npm i vue-countup-v3
``` vue
<script setup lang="ts">
import CountUp from 'vue-countup-v3'
</script>

<template>
  <count-up :end-val="2000"></count-up>
</template>
```
不管是VS还是WB，都会对引入vue-countup-v3报错，使用没问题，但是如果开了ts any校验，就没法构建成功

**Comment by jizai1125** [comment]
我发包了，更新到 1.4.0 就行了
之前的版本可以把包 package.json 中的 exports 去掉，或者 exports 里面加个 types
<img width="538" alt="image" src="https://github.com/jizai1125/vue-countup-v3/assets/33979706/91514b0a-3238-4e82-9808-f05e5dcb44d9">
