### ISSUE TITLE
页面上使用多个count-up 配合Odometer翻牌器动画   渲染会有问题  页面上只能看到一个count-up

### ISSUE THREAD

**Issue by ZZZyyyf** [jizai1125/vue-countup-v3#22]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jizai1125** [comment]
你用法有问题吧，我试了没问题
https://codesandbox.io/p/sandbox/vue-countup-v3-demo-odometer-plugin-gvnyky?file=%2Fsrc%2FApp.vue
