### ISSUE TITLE
引入组件报错

### ISSUE THREAD

**Issue by Chen-Sanyuan** [jizai1125/vue-countup-v3#23]
![image](https://github.com/jizai1125/vue-countup-v3/assets/102019590/6eb48c3d-2255-474c-8c13-7c9f6dcd38b8)

**Comment by Chen-Sanyuan** [comment]
我只在index.html中增加了cdn资源，并在页面import，我不确定这种方式是否正确
![image](https://github.com/jizai1125/vue-countup-v3/assets/102019590/315ddbac-6404-465c-82af-c5357bb9c3ad)

**Comment by jizai1125** [comment]
改成 umd 格式 vue-countup-v3.umd.js

**Comment by Chen-Sanyuan** [comment]
已经修改，但是出现了新的错误
![image](https://github.com/user-attachments/assets/13971c1b-9194-4e4f-bccf-218fdec17e3c)
![image](https://github.com/user-attachments/assets/3c402b4a-abaa-47e4-b2bd-eeae438bc827)

**Comment by jizai1125** [comment]
你看看 readme 里面的示例

**Comment by Chen-Sanyuan** [comment]
是指需要添加    
<script>
        const app = Vue.createApp({})
        app.component('CountUp', VueCountUp)
        app.mount('#app')
</script>么？

**Comment by jizai1125** [comment]
> 是指需要添加
> 
> <script> const app = Vue.createApp({}) app.component('CountUp', VueCountUp) app.mount('#app') </script>么？

看你的报错，不清楚啥原因导致的，可以提供个在线示例
