### ISSUE TITLE
小数点精度丢失 能否解决

### ISSUE THREAD

**Issue by Reset0921** [jizai1125/vue-countup-v3#4]
试过vue-count-to针对vue2.x的api decimals="2"也无效

**Comment by jizai1125** [comment]
能给个复现么

**Comment by Reset0921** [comment]
<count-up :start-val="0" :end-val="200.00" :decimals="2"></count-up>就像这样 页面只能显示200

**Comment by Reset0921** [comment]
‘’<count-up :start-val="0" :end-val="200.00" :decimals="2"></count-up>‘’

**Comment by Reset0921** [comment]
你把end-val传入200.00这类的数字 页面就只显示200了

**Comment by jizai1125** [comment]
贴下代码看看，你配置了 `decimalPlaces` 没有
