### ISSUE TITLE
Options don't work properly if used enableScrollSpy, scrollSpyDelay, scrollSpyOnce

### ISSUE THREAD

**Issue by ktm72** [jizai1125/vue-countup-v3#6]
Options don't work properly if used enableScrollSpy, scrollSpyDelay, scrollSpyOnce.

Count in template:
<CountUp
      :end-val="4073"
      :duration="1"
      :options="options"
 ></CountUp>

**Additional context**
import { ref } from "vue";
import CountUp from "vue-countup-v3";
export default {
  name: "Counter",
  components: {
    CountUp,
  },
  setup() {
    const options = ref({
      enableScrollSpy: true,
      scrollSpyDelay: 100,
      scrollSpyOnce: true,
    });
    return {
      options,
    };
  },

It stopped at 0.

**Comment by jizai1125** [comment]
I tried it and there's no problem. Can you provide a reproduction?
https://codesandbox.io/s/strange-leavitt-fw8cpz?file=/src/App.vue:1162-1170

**Comment by ktm72** [comment]
@jizai1125 Yeah. I tried the above in pnpm vite vue project. Works perfectly. But don't know why it's not working in my npm vue cli project. Strange. At the project, I used jquery for some reasons. Could it affect the countup anyway?
BTW, Thanks for the immediate reply.

**Comment by jizai1125** [comment]
@ktm72 Can you provide a minimal reproduction or upgrade to the latest version and try again? If you have set `enableScrollSpy` to `true`, make sure to set the component prop `autoplay` to `false`.
