### ISSUE TITLE
用这个还需要装countup.js吗

### ISSUE THREAD

**Issue by dhj0326** [jizai1125/vue-countup-v3#7]
我也是vite+vue3项目
然后之前安装countup.js 安装完启动项目控制台报countup.js 504之类的，项目不能正常启动，您有遇到过吗

**Comment by jizai1125** [comment]
不需要装 countup.js，报错能给个复现么

**Comment by dhj0326** [comment]
因为我的数值是请求出来的。所以我想等请求完在进行数值滚动，能问一下怎么设置吗？

**Comment by jizai1125** [comment]
> 因为我的数值是请求出来的。所以我想等请求完在进行数值滚动，能问一下怎么设置吗？

结束值 `end-val` 绑定响应式变量就行
https://codesandbox.io/s/immutable-fire-uqdpwi?file=/src/App.vue

**Comment by dhj0326** [comment]
谢谢
