### ISSUE TITLE
使用vite构建代码的时候，发现会报这个错误 To load an ES module....

### ISSUE THREAD

**Issue by bilibala2** [jizai1125/vue-countup-v3#8]
`(node:30639) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
.../node_modules/.pnpm/vue-countup-v3@1.2.0_vue@3.2.47/node_modules/vue-countup-v3/dist/vue-countup-v3.es.js:20
import { defineComponent, ref, watch, onMounted, onUnmounted, openBlock, createElementBlock, renderSlot, createElementVNode } from "vue";`
在 vue-countup-v3 的package.json文件中加上  "type": "module", 才可以打包成功，这个可以做兼容吗？或者有其他解决方案可以参考吗？

**Comment by jizai1125** [comment]
能给个复现么

**Comment by bilibala2** [comment]
可能是因为我的主项目的 package.json 文件就是要求 "type": "module"，所以会出现这个错误，但这个要求我没有办法更改。
主项目的 package.json 部分内容如下：
`"type": "module","private": true,`
`"vue": "^3.2.47"`

引入代码：
`<script setup lang="ts">
import CountUp from 'vue-countup-v3';

const { endVal = 384200 } = defineProps<{
	endVal: number;
}>()
</script>

<template>
	<count-up class="w-full text-8 mb-5" :end-val="endVal" :duration="5"></count-up>
</template>`

使用命令： npm build 执行代码构建。
修改 /node_modules 文件夹中的 vue-countup-v3 的 package.json 文件：
`"types": "dist/countup.vue.d.ts",
  "type": "module",`
只是加上了 "type": "module", 就可以构建成功。
但是加上了这个之后，npm run dev 就会报错，必须要去掉才可以运行成功。

**Comment by jizai1125** [comment]
你是在 nuxt 中用的？配置下 `build.transpile`, 参考 [issue](https://github.com/nuxt/nuxt/issues/12233)
```ts
import { defineNuxtConfig } from 'nuxt3';

export default defineNuxtConfig({
  build: {
    transpile: ['vue-countup-v3'],
  },
});
```

**Comment by bilibala2** [comment]
我的项目并不是 nuxt 框架的，而是使用 astro+vue3

**Comment by jizai1125** [comment]
> 我的项目并不是 nuxt 框架的，而是使用 astro+vue3

加个指令 `client:only`

```vue
  <CountUp client:load client:only end-val={2000} />
```
相关 issue: https://github.com/withastro/astro/issues/6321
