### ISSUE TITLE
希望能增加一个不处理小数点的配置

### ISSUE THREAD

**Issue by panmqd1** [jizai1125/vue-countup-v3#9]
目前默认整数, 配置项也只能是数字, 我希望我传入带小数的数字时, 小数位能够原样返回

**Comment by jizai1125** [comment]
配了 `decimalPlaces` 没有

**Comment by panmqd1** [comment]
decimalPlaces只接受数字和undefined, 我看里面的实现是直接传递给toFixed做参数了, 靠配置是没办法实现不处理小数点的

**Comment by jizai1125** [comment]
> @panmqd1 我希望我传入带小数的数字时, 小数位能够原样返回

你说的这效果是什么意思？没太明白，是小数位不做动画处理？如果是这效果的话，你要不就不设置 `decimalPlaces`，然后小数位用插槽的形式传入？
```vue
<template>
  <count-up :end-val="endValRef" :options="{ suffix: decimalsRef }"></count-up>
</template>

<script setup>
import { ref, computed } from "vue";
import CountUp from "vue-countup-v3";

const endValRef = ref(2022.22);

const decimalsRef = computed(() => {
  const d = /\d+.(\d+)/.exec(endValRef.value);
  return d ? `.${d[1]}` : "";
});
</script>
```
或者用 `options.formattingFn` 处理下

**Comment by panmqd1** [comment]
这个方案我试了一下通过函数来动态获取endVal的小数位数, 没有生效, 等我明天再看看吧, 谢谢你

**Comment by jizai1125** [comment]
> 这个方案我试了一下通过函数来动态获取endVal的小数位数, 没有生效, 等我明天再看看吧, 谢谢你

我试了可以的，我后面把这个拓展处理下放进组件

**Comment by panmqd1** [comment]
好的, 谢谢
